### ISSUE TITLE
Reduce coupling of functions in consolidate.py

### ISSUE THREAD

**Issue by sander2825** [hsbc/pyratings#37]
Currently, when computing a portfolio average short-term rating, we :

1. clean the ratings using _get_pure_ratings_
2. consolidate the ratings (i.e. convert ST ratings into AEV scores, identify the proper number - highest for worst rating, lowest for best rating... - and translate it back to ST rating) using _get_worst_ratings_, _get_best_ratings_  or _get_second_best_ratings_
3. get AEV scores from the consolidated ratings using _get_scores_from_ratings_
4. calculate the AEV score average using _get_weighted_average_
5. go back to ST ratings using _get_ratings_from_scores_

The fact of going back and forth from AEV scores to ratings in steps 2 and 3 may introduce a bias. Let's consider a security rated P-1 by Moody's and F1+ by Fitch. It translates into AEV scores of respectively 3.5 and 3. The worst score would then be **3.5**. 
But directly using _get_worst_ratings_ (with the default 'S&P' value for the 'rating_provider_output' parameter) on the P-1 and F1+ ratings, we end up with  A-1+ which would translate in **2.5** using _get_scores_from_ratings_ .

A solution would be to introduce _get_worst_scores_, _get_best_scores_  or _get_second_best_scores_ which only convert ST ratings into AEV scores and identify the proper number but would replace steps 2 and 3.

What do you think?

**Comment by a-vester** [comment]
This is a valid point. It is also true for computing the average portfolio long-term rating.

We are translating ratings into scores to identify the lowest/second lowest/highest score when computing the best/second best/worst rating, Subsequently, we are translating back into a human-readable rating.  
When computing the average rating, we are again translating the same ratings back into scores and vice versa. This involves unnecessary computations.

The functions ``get_best_ratings``, ``get_second_best_ratigs``, and ``get_worst_ratings`` all make use of ``get_scores_from_ratings``.
https://github.com/hsbc/pyratings/blob/5434d9333b8e958d0b7eae628caf18d95f65470a/src/pyratings/consolidate.py#L83-L86

Your suggestion to introduce new functions ``get_best_scores``, ``get_second_best_scores``, and ``get_worst_scores`` will indeed reduce coupling between these individual functions.
